# Generated by Django 3.2.16 on 2023-01-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logbook_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grade', models.CharField(default='Driver', max_length=25)),
                ('driver_name', models.CharField(max_length=50)),
                ('driver_email', models.EmailField(blank=True, max_length=254)),
                ('unit', models.IntegerField(default=29)),
                ('location_at_time_of_fault', models.TextField()),
                ('details_of_defect', models.TextField()),
                ('report_read', models.BooleanField(default=False)),
                ('work_order_created', models.BooleanField(default=False)),
                ('driver_responded_to', models.BooleanField(default=False)),
            ],
        ),
    ]
