# Generated by Django 3.2.16 on 2023-02-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook_report',
            name='report_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logbook_report',
            name='time_of_fault',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logbook_report',
            name='location_at_time_of_fault',
            field=models.TextField(max_length=60),
        ),
    ]
