# Generated by Django 3.2.16 on 2023-02-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20230203_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook_report',
            name='date_of_fault',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='logbook_report',
            name='driver_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='logbook_report',
            name='unit',
            field=models.IntegerField(default=29, max_length=5),
        ),
    ]
