# Generated by Django 3.2.16 on 2023-02-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20230209_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook_report',
            name='work_order_closed',
            field=models.BooleanField(default=False),
        ),
    ]
