# Generated by Django 3.2.16 on 2023-02-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_logbook_report_work_order_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook_report',
            name='unit',
            field=models.IntegerField(default=29),
        ),
    ]
