# Generated by Django 3.2.16 on 2023-02-12 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_logbook_report_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logbook_report',
            options={'ordering': ['date_of_fault']},
        ),
    ]
