# Generated by Django 3.2.16 on 2023-02-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_alter_logbook_report_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logbook_report',
            name='report_approved',
        ),
    ]
