# Generated by Django 3.2.16 on 2023-02-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_remove_logbook_report_report_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook_report',
            name='Depot_feedback',
            field=models.TextField(default='Copy SAP longtext here', max_length=300),
        ),
    ]
