# Generated by Django 3.2.16 on 2023-02-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_logbook_report_depot_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook_report',
            name='work_order_number',
            field=models.IntegerField(null=True),
        ),
    ]
