# Generated by Django 3.2.16 on 2023-02-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_logbook_report_work_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook_report',
            name='work_order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
